export const mockData = [
  {
    location: {
      lon: 789,
      lat: 12345.6,
    },
    quantity: 4,
    description: '3 bojler van elado',
    unit: 'darab',
    categoryId: '4',
    userId: 'gKZRPJOskOgVI477lUihL3RswLe2',
    type: 'OFFER',
  },
  {
    userId: 'gKZRPJOskOgVI477lUihL3RswLe2',
    type: 'OFFER',
    location: {
      lon: 789,
      lat: 12345.6,
    },
    quantity: 4,
    description: '3 bojler van elado',
    unit: 'darab',
    categoryId: '4',
  },
  {
    location: {
      lat: 12345.6,
      lon: 789,
    },
    quantity: 4,
    description: '3 bojler van elado',
    unit: 'darab',
    categoryId: '4',
    userId: 'gKZRPJOskOgVI477lUihL3RswLe2',
    type: 'REQUEST',
  },
  {
    unit: 'darab',
    categoryId: '4',
    userId: 'gKZRPJOskOgVI477lUihL3RswLe2',
    type: 'OFFER',
    location: {
      lon: 789,
      lat: 12345.6,
    },
    quantity: 4,
    description: '3 bojler van elado',
  },
  {
    unit: 'darab',
    categoryId: '4',
    userId: 'gKZRPJOskOgVI477lUihL3RswLe2',
    type: 'REQUEST',
    location: {
      lon: 789,
      lat: 12345.6,
    },
    quantity: 4,
    description: '3 bojler van elado',
  },
  {
    categoryId: '4',
    userId: 'gKZRPJOskOgVI477lUihL3RswLe2',
    type: 'REQUEST',
    location: {
      lon: 789,
      lat: 12345.6,
    },
    quantity: 4,
    description: '3 bojler van elado',
    unit: 'darab',
  },
  {
    unit: 'darab',
    categoryId: '4',
    userId: 'gKZRPJOskOgVI477lUihL3RswLe2',
    type: 'OFFER',
    location: {
      lat: 12345.6,
      lon: 789,
    },
    quantity: 4,
    description: '3 bojler van elado',
  },
  {
    userId: 'gKZRPJOskOgVI477lUihL3RswLe2',
    type: 'REQUEST',
    location: {
      lat: 12345.6,
      lon: 789,
    },
    quantity: 4,
    description: '3 bojler van elado',
    unit: 'darab',
    categoryId: '4',
  },
  {
    unit: 'darab',
    categoryId: '4',
    userId: 'gKZRPJOskOgVI477lUihL3RswLe2',
    type: 'REQUEST',
    location: {
      lat: 12345.6,
      lon: 789,
    },
    quantity: 4,
    description: '3 bojler van elado',
  },
  {
    type: 'REQUEST',
    location: {
      lat: 12345.6,
      lon: 789,
    },
    quantity: 4,
    description: '3 bojler van elado',
    unit: 'darab',
    categoryId: '4',
    userId: 'gKZRPJOskOgVI477lUihL3RswLe2',
  },
  {
    type: 'REQUEST',
    location: {
      lon: 789,
      lat: 12345.6,
    },
    quantity: 4,
    description: '3 bojler van elado',
    unit: 'darab',
    categoryId: '4',
    userId: 'gKZRPJOskOgVI477lUihL3RswLe2',
  },
  {
    unit: 'darab',
    categoryId: '4',
    userId: 'gKZRPJOskOgVI477lUihL3RswLe2',
    type: 'OFFER',
    location: {
      lat: 12345.6,
      lon: 789,
    },
    quantity: 4,
    description: '3 bojler van elado',
  },
  {
    type: 'REQUEST',
    location: {
      lon: 789,
      lat: 12345.6,
    },
    quantity: 4,
    description: '3 bojler van elado',
    unit: 'darab',
    categoryId: '4',
    userId: 'gKZRPJOskOgVI477lUihL3RswLe2',
  },
  {
    unit: 'darab',
    categoryId: '4',
    userId: 'gKZRPJOskOgVI477lUihL3RswLe2',
    type: 'OFFER',
    location: {
      lat: 12345.6,
      lon: 789,
    },
    quantity: 4,
    description: '3 bojler van elado',
  },
  {
    unit: 'darab',
    categoryId: '1',
    userId: 'gKZRPJOskOgVI477lUihL3RswLe2',
    type: 'REQUEST',
    location: {
      lon: 789,
      lat: 12345.6,
    },
    quantity: 4,
    description: '777 bojler van elado',
  },
  {
    location: {
      lat: 12345.6,
      lon: 789,
    },
    quantity: 4,
    description: '3 bojler van elado',
    unit: 'darab',
    categoryId: '4',
    userId: 'gKZRPJOskOgVI477lUihL3RswLe2',
    type: 'REQUEST',
  },
  {
    description: '3 bojler van elado',
    unit: 'darab',
    categoryId: '4',
    userId: 'gKZRPJOskOgVI477lUihL3RswLe2',
    type: 'REQUEST',
    location: {
      lon: 789,
      lat: 12345.6,
    },
    quantity: 4,
  },
  {
    unit: 'darab',
    categoryId: '4',
    userId: 'gKZRPJOskOgVI477lUihL3RswLe2',
    type: 'REQUEST',
    location: {
      lon: 789,
      lat: 12345.6,
    },
    quantity: 4,
    description: '3 bojler van elado',
  },
  {
    description: '3 bojler van elado',
    unit: 'darab',
    categoryId: '4',
    userId: 'gKZRPJOskOgVI477lUihL3RswLe2',
    type: 'REQUEST',
    location: {
      lat: 12345.6,
      lon: 789,
    },
    quantity: 4,
  },
  {
    description: '3 bojler van elado',
    unit: 'darab',
    categoryId: '4',
    userId: 'gKZRPJOskOgVI477lUihL3RswLe2',
    type: 'REQUEST',
    location: {
      lon: 789,
      lat: 12345.6,
    },
    quantity: 4,
  },
  {
    type: 'REQUEST',
    location: {
      lon: 789,
      lat: 12345.6,
    },
    quantity: 4,
    description: '3 bojler van elado',
    unit: 'darab',
    categoryId: '4',
    userId: 'gKZRPJOskOgVI477lUihL3RswLe2',
  },
  {
    unit: 'darab',
    categoryId: '4',
    userId: 'gKZRPJOskOgVI477lUihL3RswLe2',
    type: 'REQUEST',
    location: {
      lon: 789,
      lat: 12345.6,
    },
    quantity: 4,
    description: '3 bojler van elado',
  },
  {
    location: {
      lat: 12345.6,
      lon: 789,
    },
    quantity: 4,
    description: '3 bojler van elado',
    unit: 'darab',
    categoryId: '4',
    userId: 'gKZRPJOskOgVI477lUihL3RswLe2',
    type: 'OFFER',
  },
  {
    location: {
      lon: 789,
      lat: 12345.6,
    },
    quantity: 4,
    description: '3 bojler van elado',
    unit: 'darab',
    categoryId: '4',
    userId: 'gKZRPJOskOgVI477lUihL3RswLe2',
    type: 'REQUEST',
  },
  {
    unit: 'darab',
    categoryId: '4',
    userId: 'gKZRPJOskOgVI477lUihL3RswLe2',
    type: 'REQUEST',
    location: {
      lon: 789,
      lat: 12345.6,
    },
    quantity: 4,
    description: '3 bojler van elado',
  },
  {
    categoryId: '4',
    userId: 'gKZRPJOskOgVI477lUihL3RswLe2',
    type: 'REQUEST',
    location: {
      lat: 12345.6,
      lon: 789,
    },
    quantity: 4,
    description: '3 bojler van elado',
    unit: 'darab',
  },
  {
    location: {
      lon: 789,
      lat: 12345.6,
    },
    quantity: 4,
    description: '3 bojler van elado',
    unit: 'darab',
    categoryId: '4',
    userId: 'gKZRPJOskOgVI477lUihL3RswLe2',
    type: 'OFFER',
  },
  {
    type: 'OFFER',
    location: {
      lon: 789,
      lat: 12345.6,
    },
    quantity: 4,
    description: '3 bojler van elado',
    unit: 'darab',
    categoryId: '4',
    userId: 'gKZRPJOskOgVI477lUihL3RswLe2',
  },
  {
    type: 'REQUEST',
    location: {
      lon: 789,
      lat: 12345.6,
    },
    quantity: 4,
    description: '3 bojler van elado',
    unit: 'darab',
    categoryId: '4',
    userId: 'gKZRPJOskOgVI477lUihL3RswLe2',
  },
  {
    location: {
      lon: 789,
      lat: 12345.6,
    },
    quantity: 4,
    description: '3 bojler van elado',
    unit: 'darab',
    categoryId: '4',
    userId: 'gKZRPJOskOgVI477lUihL3RswLe2',
    type: 'OFFER',
  },
  {
    description: '3 bojler van elado',
    unit: 'darab',
    categoryId: '4',
    userId: 'gKZRPJOskOgVI477lUihL3RswLe2',
    type: 'OFFER',
    location: {
      lon: 789,
      lat: 12345.6,
    },
    quantity: 4,
  },
  {
    userId: 'gKZRPJOskOgVI477lUihL3RswLe2',
    type: 'REQUEST',
    location: {
      lon: 789,
      lat: 12345.6,
    },
    quantity: 4,
    description: '3 bojler van elado',
    unit: 'darab',
    categoryId: '4',
  },
  {
    userId: 'gKZRPJOskOgVI477lUihL3RswLe2',
    type: 'REQUEST',
    location: {
      lat: 12345.6,
      lon: 789,
    },
    quantity: 4,
    description: '3 bojler van elado',
    unit: 'darab',
    categoryId: '4',
  },
  {
    categoryId: '4',
    userId: 'gKZRPJOskOgVI477lUihL3RswLe2',
    type: 'REQUEST',
    location: {
      lat: 12345.6,
      lon: 789,
    },
    quantity: 4,
    description: '3 bojler van elado',
    unit: 'darab',
  },
  {
    userId: 'gKZRPJOskOgVI477lUihL3RswLe2',
    type: 'REQUEST',
    location: {
      lon: 789,
      lat: 12345.6,
    },
    quantity: 4,
    description: '3 bojler van elado',
    unit: 'darab',
    categoryId: '4',
  },
  {
    unit: 'darab',
    categoryId: '4',
    userId: 'gKZRPJOskOgVI477lUihL3RswLe2',
    type: 'REQUEST',
    location: {
      lon: 789,
      lat: 12345.6,
    },
    quantity: 4,
    description: '3 bojler van elado',
  },
  {
    categoryId: '4',
    userId: 'gKZRPJOskOgVI477lUihL3RswLe2',
    type: 'REQUEST',
    location: {
      lon: 789,
      lat: 12345.6,
    },
    quantity: 4,
    description: '3 bojler van elado',
    unit: 'darab',
  },
  {
    unit: 'darab',
    categoryId: '4',
    userId: 'gKZRPJOskOgVI477lUihL3RswLe2',
    type: 'REQUEST',
    location: {
      lat: 12345.6,
      lon: 789,
    },
    quantity: 4,
    description: '3 bojler van elado',
  },
  {
    userId: 'gKZRPJOskOgVI477lUihL3RswLe2',
    type: 'REQUEST',
    location: {
      lat: 12345.6,
      lon: 789,
    },
    quantity: 4,
    description: '3 bojler van elado',
    unit: 'darab',
    categoryId: '4',
  },
  {
    type: 'REQUEST',
    location: {
      lat: 12345.6,
      lon: 789,
    },
    quantity: 4,
    description: '3 bojler van elado',
    unit: 'darab',
    categoryId: '4',
    userId: 'gKZRPJOskOgVI477lUihL3RswLe2',
  },
  {
    location: {
      lon: 789,
      lat: 12345.6,
    },
    quantity: 4,
    description: '3 bojler van elado',
    unit: 'darab',
    categoryId: '4',
    userId: 'gKZRPJOskOgVI477lUihL3RswLe2',
    type: 'OFFER',
  },
  {
    description: '3 bojler van elado',
    unit: 'darab',
    categoryId: '4',
    userId: 'gKZRPJOskOgVI477lUihL3RswLe2',
    type: 'OFFER',
    location: {
      lat: 12345.6,
      lon: 789,
    },
    quantity: 4,
  },
];
